package com.focusapp.blocker.ui

import androidx.compose.runtime.compositionLocalOf

// ============================================================
// AppStrings — all localizable UI strings
// ============================================================

data class AppStrings(
    // Tabs
    val tabHome: String,
    val tabBlock: String,
    val tabWhitelist: String,
    val tabMotivation: String,

    // SupportHeader
    val contactUs: String,
    val supportUs: String,

    // Settings dialog
    val settingsTitle: String,
    val settingsLanguage: String,
    val settingsTheme: String,
    val themeLight: String,
    val themeDark: String,
    val themeSystem: String,

    // Stats
    val activeRules: String,
    val sectionBlocked: String,
    val sectionWhitelisted: String,
    val statApps: String,
    val statKeywords: String,
    val statSites: String,

    // Common
    val close: String,
    val cancel: String,
    val add: String,
    val undo: String,
    val set_: String,
    val protected_: String,

    // Coffee dialog
    val supportUsDialogTitle: String,
    val supportUsBody: String,
    val thankYou: String,
    val tipsUnavailable: String,

    // Permission cards
    val enablePermTitle: String,
    val enablePermBody: String,
    val openAccessibilitySettings: String,
    val batteryOptTitle: String,
    val batteryOptBody: String,
    val disableBatteryOpt: String,
    val overlayPermTitle: String,
    val overlayPermBody: String,
    val grantPermission: String,
    val miuiAutostartTitle: String,
    val miuiAutostartBody: String,
    val enableAutostart: String,
    val miuiOverlayTitle: String,
    val miuiOverlayBody: String,
    val miuiOverlayPerm1: String,
    val miuiOverlayPerm2: String,
    val openOtherPermissions: String,

    // Protection card
    val protectionTitle: String,
    val deletionProtTitle: String,
    val deletionProtSubtitle: String,
    val lock24hTitle: String,
    val lock24hSubtitle: String,
    val lock24hWarningTitle: String,
    val lock24hWarningBody: String,
    val lock24hWarningConfirm: String,
    val hideIconTitle: String,
    val hideIconSubtitle: String,
    val protectSettingsTitle: String,
    val protectSettingsOff: String,
    val protectSettingsLow: String,
    val protectSettingsHigh: String,
    val levelOff: String,
    val levelLow: String,
    val levelHigh: String,
    val loweringToLevel: (String, Long) -> String,

    // Additional Blocking card
    val additionalBlockingTitle: String,
    val adultBlockingTitle: String,
    val adultBlockingSubtitle: String,
    val adultLevelOff: String,
    val adultLevelSites: String,
    val adultLevelStrict: String,
    val blockShortsTitle: String,
    val blockShortsSubtitle: String,
    val blockReelsTitle: String,
    val blockReelsSubtitle: String,

    // Pending changes / toggle rows
    val disablingInHours: (Long) -> String,
    val scheduledChangesTitle: (Int) -> String,
    val scheduledChangesBody: String,
    val hoursLeft: (Long) -> String,

    // Block page
    val blockedAppsTitle: String,
    val blockedKeywordsTitle: String,
    val blockedWebsitesTitle: String,
    val searchApps: String,
    val pickFromApps: String,
    val noAppsFound: String,
    val removingInHours: (Long) -> String,
    val willBeWhitelistedIn: (Long) -> String,

    // Whitelist page
    val whitelistedAppsTitle: String,
    val whitelistedWebsitesTitle: String,
    val whitelistedKeywordsTitle: String,

    // Motivation page
    val durationTitle: String,
    val durationSubtitle: (Int) -> String,
    val lockDuration: String,
    val unlockDuration: String,
    val unlockingInHours: (Long) -> String,
    val durationLockedWithLock: String,
    val durationLockedWithoutLock: String,
    val durationSec: String,
    val durationLabel: String,
    val maxDuration: String,
    val contentProtTitle: String,
    val contentProtLocked: String,
    val contentProtUnlocked: String,
    val lockContent: String,
    val unlockContent: String,
    val contentLockedWithLock: String,
    val contentLockedWithoutLock: String,
    val whenToShowTitle: String,
    val motivOnBlockTitle: String,
    val motivOnBlockSubtitle: String,
    val motivOnSettingsTitle: String,
    val motivOnSettingsSubtitle: String,
    val sectionMotivVideos: String,
    val sectionChannels: String,
    val sectionPhrases: String,
    val sectionGallery: String,
    val emptyVideosHint: String,
    val emptyChannelsHint: String,
    val emptyPhrasesHint: String,
    val emptyGalleryHint: String,
    val addVideoTitle: String,
    val addVideoHint: String,
    val addChannelTitle: String,
    val addChannelHint: String,
    val addPhraseTitle: String,
    val addPhraseHint: String,
    val labelOptional: String,
    val labelAutoFetch: String,
    val unsupportedPlatform: String,
    val testRandom: String,
    val showLess: String,
    val showMore: (Int) -> String,
    val rememberYourWhy: String,
    val stayStrong: String,

    // formatChangeType map
    val changeTypeMap: Map<String, String>
)

// Extension function for formatChangeType
fun AppStrings.formatChangeType(type: String): String =
    changeTypeMap[type] ?: type

// ============================================================
// English strings
// ============================================================

val EnglishStrings = AppStrings(
    tabHome = "Home",
    tabBlock = "Block",
    tabWhitelist = "Whitelist",
    tabMotivation = "Motivation",

    contactUs = "Contact Us",
    supportUs = "Support Us",

    settingsTitle = "Settings",
    settingsLanguage = "Language",
    settingsTheme = "Theme",
    themeLight = "Light",
    themeDark = "Dark",
    themeSystem = "System",

    activeRules = "Active Rules",
    sectionBlocked = "Blocked",
    sectionWhitelisted = "Whitelisted",
    statApps = "Apps",
    statKeywords = "Keywords",
    statSites = "Sites",

    close = "Close",
    cancel = "Cancel",
    add = "Add",
    undo = "Undo",
    set_ = "Set",
    protected_ = "Protected",

    supportUsDialogTitle = "☕ Support Us",
    supportUsBody = "Every contribution helps keep the app free and improving.",
    thankYou = "Thank you so much! 💙\nYour support means a lot to us.",
    tipsUnavailable = "In-app tips aren't available on this device.",

    enablePermTitle = "⚠️ Enable Permissions",
    enablePermBody = "1. Tap the button below\n2. Go to \"Downloaded apps → Focus Blocker\"\n3. Toggle \"Use Focus Blocker\" ON",
    openAccessibilitySettings = "Open Accessibility Settings",
    batteryOptTitle = "⚡ Battery Optimization",
    batteryOptBody = "Android may stop blocking after 1-2 days unless battery optimization is disabled. Tap below → find Focus Blocker under \"Active apps\" → tap \"Put apps to sleep\" → then tap it again under \"Sleeping apps\" → select \"No restrictions\".",
    disableBatteryOpt = "Disable Battery Optimization",
    overlayPermTitle = "🪟 Display Pop-up Permission",
    overlayPermBody = "Required so the app can reopen itself when you try to access protected settings. Tap below and enable \"Display pop-up windows\".",
    grantPermission = "Grant Permission",
    miuiAutostartTitle = "🚀 Enable Autostart (MIUI)",
    miuiAutostartBody = "MIUI/Poco restricts apps from starting automatically. Enable Autostart so the blocker can restart itself after a reboot and reopen when you access protected settings.",
    enableAutostart = "Enable Autostart",
    miuiOverlayTitle = "🪟 Allow Pop-up Windows (MIUI)",
    miuiOverlayBody = "MIUI/Poco requires two permissions so the app can reopen itself when you access protected settings. Open \"Other permissions\" and enable both:",
    miuiOverlayPerm1 = "Open new windows while running in the background",
    miuiOverlayPerm2 = "Display pop-up windows",
    openOtherPermissions = "Open Other Permissions",

    protectionTitle = "Protection",
    deletionProtTitle = "Deletion Protection",
    deletionProtSubtitle = "Prevents uninstall via Device Admin",
    lock24hTitle = "24h Lock",
    lock24hSubtitle = "Duration unlock & disabling this require 24h",
    lock24hWarningTitle = "Enable 24h Lock?",
    lock24hWarningBody = "Once enabled, turning off any blocked app, website, keyword, or protection setting will take ~24 hours to take effect.\n\nYou will not be able to undo this instantly.",
    lock24hWarningConfirm = "Enable Lock",
    hideIconTitle = "Hide App Icon",
    hideIconSubtitle = "Remove the app from the home screen and app drawer",
    protectSettingsTitle = "Protect Settings",
    protectSettingsOff = "Off — settings are not protected",
    protectSettingsLow = "Low — blocks pages where permissions can be changed",
    protectSettingsHigh = "High — blocks all settings pages mentioning this app",
    levelOff = "Off",
    levelLow = "Low",
    levelHigh = "High",
    loweringToLevel = { level, h -> "⏳ Lowering to $level in ~${h}h" },

    additionalBlockingTitle = "Additional Blocking",
    adultBlockingTitle = "Adult Content Blocking",
    adultBlockingSubtitle = "Block adult websites and keywords",
    adultLevelOff = "Off",
    adultLevelSites = "Sites",
    adultLevelStrict = "Strict",
    blockShortsTitle = "Block YouTube Shorts",
    blockShortsSubtitle = "Redirects to YouTube home when Shorts is opened",
    blockReelsTitle = "Block Instagram Reels",
    blockReelsSubtitle = "Redirects to Instagram home when Reels is opened",

    disablingInHours = { "⏳ Disabling in ~${it}h" },
    scheduledChangesTitle = { "⏳ Scheduled Changes ($it)" },
    scheduledChangesBody = "These changes will take effect after 24 hours. Tap × to cancel.",
    hoursLeft = { "~${it}h" },

    blockedAppsTitle = "Blocked Apps",
    blockedKeywordsTitle = "Blocked Keywords",
    blockedWebsitesTitle = "Blocked Websites",
    searchApps = "Search apps...",
    pickFromApps = "Pick from Installed Apps",
    noAppsFound = "No apps found",
    removingInHours = { "⏳ Removing in ~${it}h" },
    willBeWhitelistedIn = { "⏳ Will be whitelisted in ~${it}h" },

    whitelistedAppsTitle = "Whitelisted Apps",
    whitelistedWebsitesTitle = "Whitelisted Websites",
    whitelistedKeywordsTitle = "Whitelisted Keywords",

    durationTitle = "Unskippable Duration",
    durationSubtitle = { "Plays for ${it}s before you can skip" },
    lockDuration = "Lock duration",
    unlockDuration = "Unlock duration",
    unlockingInHours = { "⏳ Unlocking in ~${it}h" },
    durationLockedWithLock = "Duration is locked. Tap 🔓 to request unlock (24h delay).",
    durationLockedWithoutLock = "Duration is locked. Tap 🔓 to unlock.",
    durationSec = "sec",
    durationLabel = "Duration",
    maxDuration = "max 300s",
    contentProtTitle = "Content Protection",
    contentProtLocked = "Add only — deletion is blocked across all sections",
    contentProtUnlocked = "Lock to prevent accidental deletion",
    lockContent = "Lock content",
    unlockContent = "Unlock content",
    contentLockedWithLock = "Tap 🔓 to request unlock (24h delay).",
    contentLockedWithoutLock = "Tap 🔓 to unlock immediately.",
    whenToShowTitle = "When to Show",
    motivOnBlockTitle = "After blocking an app",
    motivOnBlockSubtitle = "Show a motivation video when a blocked app is opened",
    motivOnSettingsTitle = "After blocking forbidden settings",
    motivOnSettingsSubtitle = "Show a motivation video when protected settings are accessed",
    sectionMotivVideos = "Motivation Videos",
    sectionChannels = "Channels",
    sectionPhrases = "Motivation Phrases",
    sectionGallery = "Gallery Videos",
    emptyVideosHint = "Add an Instagram Reel or YouTube video.",
    emptyChannelsHint = "Add a YouTube or Instagram channel.",
    emptyPhrasesHint = "Add a quote or message to inspire you when you're tempted.",
    emptyGalleryHint = "Pick a video from your device to play offline.",
    addVideoTitle = "Add Motivation Video",
    addVideoHint = "Paste YouTube or Instagram URL",
    addChannelTitle = "Add Channel",
    addChannelHint = "Paste YouTube or Instagram channel URL",
    addPhraseTitle = "Add Motivation Phrase",
    addPhraseHint = "Your motivational phrase",
    labelOptional = "Label (optional)",
    labelAutoFetch = "Auto-fetched from URL if left blank",
    unsupportedPlatform = "Only YouTube and Instagram URLs are supported",
    testRandom = "Test Random",
    showLess = "Show less",
    showMore = { "Show $it more" },
    rememberYourWhy = "Remember Your Why",
    stayStrong = "Stay strong 💪",

    changeTypeMap = mapOf(
        "remove_blocked_website" to "Remove blocked website",
        "remove_blocked_package" to "Remove blocked app",
        "remove_blocked_keyword" to "Remove blocked keyword",
        "add_whitelisted_website" to "Add whitelisted website",
        "add_whitelisted_package" to "Add whitelisted app",
        "disable_deletion_protection" to "Disable deletion protection",
        "disable_adult_blocking" to "Disable adult content blocking",
        "disable_lock" to "Disable 24h lock",
        "unlock_duration" to "Unlock motivation duration",
        "unlock_content" to "Unlock content protection",
        "show_app_icon" to "Show app icon",
        "lower_settings_protection" to "Lower settings protection",
        "disable_motivation_on_block" to "Disable motivation on block",
        "disable_motivation_on_settings" to "Disable motivation on settings"
    )
)

// ============================================================
// Hebrew strings
// ============================================================

val HebrewStrings = AppStrings(
    tabHome = "בית",
    tabBlock = "חסימות",
    tabWhitelist = "הרשאות",
    tabMotivation = "מוטיבציה",

    contactUs = "צור קשר",
    supportUs = "תמוך בנו",

    settingsTitle = "הגדרות",
    settingsLanguage = "שפה",
    settingsTheme = "ערכת נושא",
    themeLight = "בהיר",
    themeDark = "כהה",
    themeSystem = "כמערכת",

    activeRules = "חוקים פעילים",
    sectionBlocked = "חסומים",
    sectionWhitelisted = "מורשים",
    statApps = "אפליקציות",
    statKeywords = "מילות מפתח",
    statSites = "אתרים",

    close = "סגור",
    cancel = "ביטול",
    add = "הוסף",
    undo = "בטל",
    set_ = "קבע",
    protected_ = "מוגן",

    supportUsDialogTitle = "☕ תמוך בנו",
    supportUsBody = "כל תרומה עוזרת לשמור על האפליקציה חינמית ומשתפרת.",
    thankYou = "תודה רבה! 💙\nהתמיכה שלך אומרת לנו הרבה.",
    tipsUnavailable = "טיפים באפליקציה אינם זמינים במכשיר זה.",

    enablePermTitle = "⚠️ הפעל הרשאות",
    enablePermBody = "1. הקש על הכפתור למטה\n2. עבור אל \"אפליקציות שהורדת ← Focus Blocker\"\n3. הפעל \"שימוש ב-Focus Blocker\"",
    openAccessibilitySettings = "פתח הגדרות נגישות",
    batteryOptTitle = "⚡ אופטימיזציית סוללה",
    batteryOptBody = "Android עשוי להפסיק את החסימה לאחר יום-יומיים אלא אם תבטל אופטימיזציית סוללה. הקש למטה ← מצא את Focus Blocker תחת \"יישומים פעילים\" ← הקש \"הרדם יישומים\" ← הקש עליה שוב תחת \"יישומים במצב שינה\" ← בחר \"אין הגבלות\".",
    disableBatteryOpt = "בטל אופטימיזציית סוללה",
    overlayPermTitle = "🪟 הרשאת חלון קופץ",
    overlayPermBody = "נדרש כדי שהאפליקציה תוכל לפתוח את עצמה כשמנסים לגשת להגדרות מוגנות. הקש למטה ואפשר \"הצג חלונות קופצים\".",
    grantPermission = "הענק הרשאה",
    miuiAutostartTitle = "🚀 אשר הפעלה אוטומטית (MIUI)",
    miuiAutostartBody = "MIUI/Poco מגביל אפליקציות מהפעלה אוטומטית. אשר הפעלה אוטומטית ברקע כדי שהחוסם יוכל להפעיל את עצמו מחדש לאחר אתחול.",
    enableAutostart = "אשר הפעלה אוטומטית",
    miuiOverlayTitle = "🪟 אפשר חלונות קופצים (MIUI)",
    miuiOverlayBody = "MIUI/Poco דורש שתי הרשאות כדי שהאפליקציה תוכל לפתוח את עצמה. פתח \"הרשאות אחרות\" ואפשר את שניהם:",
    miuiOverlayPerm1 = "פתח חלונות חדשים בזמן ריצה ברקע",
    miuiOverlayPerm2 = "הצג חלונות קופצים",
    openOtherPermissions = "פתח הרשאות אחרות",

    protectionTitle = "הגנה",
    deletionProtTitle = "הגנה מפני מחיקה",
    deletionProtSubtitle = "מונע הסרה של האפליקציה",
    lock24hTitle = "נעילה ל-24 שעות",
    lock24hSubtitle = "שחרור חסימות וביטול נעילה דורשים 24 שעות",
    lock24hWarningTitle = "להפעיל נעילה ל-24 שעות?",
    lock24hWarningBody = "לאחר ההפעלה, ביטול כל חסימת אפליקציה, אתר, מילת מפתח או הגדרת הגנה ייקח ~24 שעות.\n\nלא ניתן לבטל זאת באופן מיידי.",
    lock24hWarningConfirm = "הפעל נעילה",
    hideIconTitle = "הסתר סמל אפליקציה",
    hideIconSubtitle = "הסר את האפליקציה ממסך הבית ומגירת האפליקציות",
    protectSettingsTitle = "הגנה על ההגדרות",
    protectSettingsOff = "כבויה — ההגדרות אינן מוגנות",
    protectSettingsLow = "נמוכה — חוסם עמודים שבהם ניתן לשנות הרשאות",
    protectSettingsHigh = "גבוהה — חוסם את כל דפי ההגדרות המזכירים אפליקציה זו",
    levelOff = "כבויה",
    levelLow = "נמוכה",
    levelHigh = "גבוהה",
    loweringToLevel = { level, h -> "⏳ מורדת ל-$level בעוד ~${h}שע׳" },

    additionalBlockingTitle = "חסימה נוספת",
    adultBlockingTitle = "חסימת תוכן 18+",
    adultBlockingSubtitle = "חסום אתרי בוגרים ומילות מפתח",
    adultLevelOff = "כבוי",
    adultLevelSites = "אתרים",
    adultLevelStrict = "קפדני",
    blockShortsTitle = "חסימת YouTube Shorts",
    blockShortsSubtitle = "מפנה לדף הבית של YouTube כשנפתח Shorts",
    blockReelsTitle = "חסימת Instagram Reels",
    blockReelsSubtitle = "מפנה לדף הבית של Instagram כש-Reels נפתח",

    disablingInHours = { "⏳ מתבטל בעוד ~${it}שע׳" },
    scheduledChangesTitle = { "⏳ שינויים מתוזמנים ($it)" },
    scheduledChangesBody = "שינויים אלה ייכנסו לתוקף לאחר 24 שעות. הקש × לביטול.",
    hoursLeft = { "~${it}שע׳" },

    blockedAppsTitle = "אפליקציות חסומות",
    blockedKeywordsTitle = "מילות מפתח חסומות",
    blockedWebsitesTitle = "אתרים חסומים",
    searchApps = "חפש אפליקציות...",
    pickFromApps = "בחר מאפליקציות מותקנות",
    noAppsFound = "לא נמצאו אפליקציות",
    removingInHours = { "⏳ מוסר בעוד ~${it}שע׳" },
    willBeWhitelistedIn = { "⏳ יאושר בעוד ~${it}שע׳" },

    whitelistedAppsTitle = "אפליקציות מורשות",
    whitelistedWebsitesTitle = "אתרים מורשים",
    whitelistedKeywordsTitle = "מילות מפתח מורשות",

    durationTitle = "משך זמן ללא דילוג",
    durationSubtitle = { "מנגן ${it} שניות לפני שניתן לדלג" },
    lockDuration = "נעל משך",
    unlockDuration = "שחרר משך",
    unlockingInHours = { "⏳ משתחרר בעוד ~${it}שע׳" },
    durationLockedWithLock = "כמות הזמן נעולה. הקש 🔓 לבקשת שחרור (24 שעות).",
    durationLockedWithoutLock = "המשך נעול. הקש 🔓 לשחרור.",
    durationSec = "שנ׳",
    durationLabel = "משך",
    maxDuration = "מקסימום 300 שנ׳",
    contentProtTitle = "הגנת תוכן",
    contentProtLocked = "הוספה בלבד — לא ניתן למחוק סרטונים מהרשימה",
    contentProtUnlocked = "נעל למניעת מחיקה בשוגג",
    lockContent = "נעל תוכן",
    unlockContent = "שחרר תוכן",
    contentLockedWithLock = "הקש 🔓 לבקשת שחרור (24 שעות).",
    contentLockedWithoutLock = "הקש 🔓 לשחרור מיידי.",
    whenToShowTitle = "מתי להציג",
    motivOnBlockTitle = "לאחר חסימת אפליקציה",
    motivOnBlockSubtitle = "הצג סרטון מוטיבציה כשאפליקציה חסומה נפתחת",
    motivOnSettingsTitle = "לאחר חסימת הגדרות אסורות",
    motivOnSettingsSubtitle = "הצג סרטון מוטיבציה כשמגיעים להגדרות מוגנות",
    sectionMotivVideos = "סרטוני מוטיבציה",
    sectionChannels = "ערוצים",
    sectionPhrases = "משפטי מוטיבציה",
    sectionGallery = "סרטונים מהגלריה",
    emptyVideosHint = "הוסף Instagram Reel או סרטון YouTube.",
    emptyChannelsHint = "הוסף ערוץ YouTube או Instagram.",
    emptyPhrasesHint = "הוסף ציטוט או הודעה שיעוררו אותך כשאתה מתפתה.",
    emptyGalleryHint = "בחר סרטון ממכשירך להפעלה ללא חיבור.",
    addVideoTitle = "הוסף סרטון מוטיבציה",
    addVideoHint = "הדבק כתובת YouTube או Instagram",
    addChannelTitle = "הוסף ערוץ",
    addChannelHint = "הדבק כתובת ערוץ YouTube או Instagram",
    addPhraseTitle = "הוסף משפט מוטיבציה",
    addPhraseHint = "משפט המוטיבציה שלך",
    labelOptional = "תווית (אופציונלי)",
    labelAutoFetch = "נשלף אוטומטית מהכתובת אם ריק",
    unsupportedPlatform = "רק כתובות YouTube ו-Instagram נתמכות",
    testRandom = "בחן באופן אקראי",
    showLess = "הצג פחות",
    showMore = { "הצג $it נוספים" },
    rememberYourWhy = "זכור את הסיבות שלך",
    stayStrong = "הישאר חזק✊",

    changeTypeMap = mapOf(
        "remove_blocked_website" to "הסרת אתר חסום",
        "remove_blocked_package" to "הסרת אפליקציה חסומה",
        "remove_blocked_keyword" to "הסרת מילת מפתח חסומה",
        "add_whitelisted_website" to "הוספת אתר מורשה",
        "add_whitelisted_package" to "הוספת אפליקציה מורשית",
        "disable_deletion_protection" to "ביטול הגנה מפני מחיקה",
        "disable_adult_blocking" to "ביטול חסימת תוכן למבוגרים",
        "disable_lock" to "ביטול נעילה ל-24 שעות",
        "unlock_duration" to "שחרור משך המוטיבציה",
        "unlock_content" to "שחרור הגנת תוכן",
        "show_app_icon" to "הצג סמל אפליקציה",
        "lower_settings_protection" to "הורד הגנת הגדרות",
        "disable_motivation_on_block" to "ביטול מוטיבציה בחסימה",
        "disable_motivation_on_settings" to "ביטול מוטיבציה בהגדרות"
    )
)

// ============================================================
// CompositionLocals
// ============================================================

val LocalStrings = compositionLocalOf<AppStrings> { EnglishStrings }
val LocalIsHebrew = compositionLocalOf { false }
val LocalOnToggleLanguage = compositionLocalOf<() -> Unit> { {} }
val LocalThemeMode = compositionLocalOf { "system" }
val LocalOnThemeChange = compositionLocalOf<(String) -> Unit> { {} }
